### ISSUE TITLE
Cannot use hooks inside of components story

### ISSUE THREAD

**Issue by lihanqi** [semoal/themeprovider-storybook#36]
**Describe the bug**
Cannot use React hooks in the story directly because of directly call on component like a fuction. I have a temporary workaround by placing the following code in front of with `addDecorator(withThemesProvider(themes));`. But I feel this might be an issue inside of `withThemesProvider`
```
`addDecorator(Story => <Story />);
````

**To Reproduce**
1. Have a story written with React Hooks
2. Go to the storybook
3. See error

**Expected behavior**
Storybook should render as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/10642680/78953786-8df9be00-7b0c-11ea-825c-4294695be4ee.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina V10.15.4
 - Browser Chrome
 - Version v80

**Comment by semoal** [comment]
Hi @lihanqi , i found the issue, i'll push a minor version, thanks for opening the issue mate.

**Comment by semoal** [comment]
Released mate, on v1.5.1, feel free to open anything out that you aren't happy.
