### ISSUE TITLE
Add themes trough shareable link as parameter

### ISSUE THREAD

**Issue by developer-bart** [semoal/themeprovider-storybook#49]
**Is your feature request related to a problem? Please describe.**
I want to share a Storybook component via the /iframe.html link. It's possible to add knobs as parameters like so: `&knob-[key]=[value]`. That doesn't seem to work for the themes.

**Describe the solution you'd like**
Being able to select a theme by adding a theme parameter. Is it already possible and am I missing stuff?

**Describe alternatives you've considered**
Changing the themes trough knobs which can be passed as parameter.

**Additional context**
x

**Comment by semoal** [comment]
Yes, it should be possible without much work. I'll try to find time as soon as possible =)

**Comment by semoal** [comment]
Released with 1.8.0 :) Basically adding `&theme=theme.name` will resolve correctly to the theme.

**Comment by developer-bart** [comment]
Wow thanks for the fast response! I much appreciate it 😃
